version: '3.8'
services:
  counter-service:
    container_name: counter-service-exercise
    image: 991962793955.dkr.ecr.eu-west-1.amazonaws.com/counter-service-exercise:latest
    volumes:
      - ./data:/data
    ports:
      - "80:8080"
    restart: always